services:
  server:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/vulnerable.com.conf:/etc/nginx/conf.d/vulnerable.com.conf:ro
      - ./frontend/templates/:/usr/share/nginx/html/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
