FROM nginx:latest
WORKDIR /etc/nginx/
COPY --chmod=400 ./*.conf ./conf.d/
COPY --chmod=400 ./*.rules ./common/
RUN rm -f /etc/nginx/conf.d/default.conf
RUN mkdir -p /etc/nginx/logs
RUN openssl req -x509 -days 365 -nodes -newkey rsa:2048 \
        -subj /CN=examle/C=RU/ST=example/O=example \
        -keyout /etc/nginx/vulnerable.com.key -text -out /etc/nginx/vulnerable.com.crt
RUN nginx -t
CMD ["nginx", "-g", "daemon off;"]
